# Generated by Django 2.1.3 on 2018-11-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')]),
        ),
    ]
